### ISSUE TITLE
Guice Interceptors (AOP) are not activated when attached to ObjectMapper based instances

### ISSUE THREAD

**Issue by cvuijst** [FasterXML/jackson-module-guice#4]
Hi,

In a Guice Injector, I tried to chain the Jackson Module Guice's ObjectMapperModule with a regular Guice Module having regular bindings (using: binder.bind()). Instance retrieval from the Guice Injector works very well, both directly from the Guice Injector and indirectly through Jackson Module Guice's ObjectMapper. 

Additionally, I tried to add a new Guice Module to the chain of Guice Modules with inside a custom Guice Interceptor (using: binder.bindInterceptor).

Instances retrieved directly from the Guice Injector show that they are instantiated from classes like: <ClassName>$$EnhancerByGuice$$25c21b02. These instances work with the Guice Interceptor as expected; method calls get redirected the Interceptor when the annotated methods get invoked.

However, instances retrieved indirectly from the Guice Injector through the ObjectMapper first show that they are instantiated from the original class names like: <ClassName> (no enhancements). Additionally, no interception (redirection) is executed on these instances when annotated methods are invoked.

Am I missing something here?

Best regards,

Charles

**Comment by cowtowncoder** [comment]
Moved to https://github.com/FasterXML/jackson-modules-base/issues/1 as part of unification of base modules.
